### ISSUE TITLE
Rotating models in SceneComposer in SDK not done correctly 

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#1]
_From @Ali-RS on March 2, 2016 19:0_

Rotating a model in scene composer is not done correctly and Parent node box not rotating along with mesh box and cause problem in transforming model in scene.
see detailed description here : 
http://hub.jmonkeyengine.org/t/bug-report-problem-with-rotating-models-in-scenecomposer-in-sdk/35224

_Copied from original issue: jMonkeyEngine/jmonkeyengine#437_

**Comment by erlend-sh** [comment]
_From @grizeldi on March 2, 2016 19:32_

I'll try to figure out where the problem lies.
Don't expect too much from a beginner though :wink:

**Comment by erlend-sh** [comment]
_From @Dokthar on March 2, 2016 23:37_

@grizeldi don't go crazy on this, you'll have to look into scenecomposer's tools (some stuff i worked on  ;) ).

**Comment by erlend-sh** [comment]
_From @grizeldi on March 3, 2016 6:42_

@Dokthar I know. Checked out the classes yesterday, added some debug printlns, but I still didn't find the void that is called when you rotate something...

**Comment by Dokthar** [comment]
created a pr #16
