### ISSUE TITLE
New Custom Control Action does only find controls that either implement Control or directly derive from AbstractControl

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#10]
_From @ghost on March 24, 2014 19:35_

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=623

_Copied from original issue: jMonkeyEngine/jmonkeyengine#105_

**Comment by grizeldi** [comment]
Was this still not fixed?

**Comment by MeFisto94** [comment]
Nope,
8bec656 is the commit that added the functionality itself but doesn't seem to be looping through the class hierarchy

**Comment by grizeldi** [comment]
Ok, I'll take a look when I have some time. Shouldn't be too hard to fix.

**Comment by MeFisto94** [comment]
Well actually the code is already provided there. If you have the time feel free to do it, only ensure that you test it before and after implementation :P

**Comment by grizeldi** [comment]
Found the part where I have to add new code. Now I just have to think of the best way to scan the class hierarchy.

**Comment by MeFisto94** [comment]
Take a look at the linked googlecode,
there already **is** the code for that, you basically would only need copy+paste :)

**Comment by grizeldi** [comment]
Yes I see. But I'm learning Netbeans API on the go, so it will take some time to figure out which code to copy pasted :)

**Comment by grizeldi** [comment]
Managed to mitigate the problem by checking if the superclass is on the list of control classes. It works if the subclass is in another package but not if it's in the same package...

Can someone point me how to check if class implements an interface? I have found on the internet that it is possible, but you need an annotation processor... Any ways to do it without one?

**Comment by Dokthar** [comment]
@grizeldi An interface is a fully abstract class (without any code) so "instance of" also works for interfaces. I think you can consider interface as a normal class.

**Comment by grizeldi** [comment]
The problem is that I don't get the actual object but an ElementType...
Never worked with those before...

**Comment by Dokthar** [comment]
maybe you can try to encapsulate the code that look for interfaces, and call that code for each super class.
