### ISSUE TITLE
Can't run "gradlew buildSdk" Linux x64

### ISSUE THREAD

**Issue by aegroto** [jMonkeyEngine/sdk#113]
If i try to run "gradlew buildSdk" an error occurs. It seems to be unable to find jme-ios for some reason,i tried to clone the repo again but the issue is still there.

Here's the log:

gradlew buildSdk
Full Version: 3.1-stable-FINAL
POM Version: 3.1.0-stable-FINAL
NBM Revision: 1700
NBM UC Suffix: stable/3.1/plugins

FAILURE: Build failed with an exception.

* Where:
Build file '/home/lorenzo/Scrivania/Varie/Progetti Java/jMonkey Engine/jmonkey nightly/sdk/build.gradle' line: 334

* What went wrong:
A problem occurred evaluating root project 'sdk'.
> Could not resolve all dependencies for configuration ':optlibs'.
   > Could not find org.jmonkeyengine:jme3-jbullet:3.1.0-stable.
     Searched in the following locations:
         file:/home/lorenzo/.m2/repository/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.pom
         file:/home/lorenzo/.m2/repository/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.jar
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.pom
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.jar
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.pom
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.jar
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.pom
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.jar
         https://jitpack.io/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.pom
         https://jitpack.io/org/jmonkeyengine/jme3-jbullet/3.1.0-stable/jme3-jbullet-3.1.0-stable.jar
     Required by:
         :sdk:unspecified
   > Could not find org.jmonkeyengine:jme3-ios:3.1.0-stable.
     Searched in the following locations:
         file:/home/lorenzo/.m2/repository/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.pom
         file:/home/lorenzo/.m2/repository/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.jar
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.pom
         http://jcenter.bintray.com/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.jar
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.pom
         http://updates.jmonkeyengine.org/maven/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.jar
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.pom
         http://nifty-gui.sourceforge.net/nifty-maven-repo/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.jar
         https://jitpack.io/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.pom
         https://jitpack.io/org/jmonkeyengine/jme3-ios/3.1.0-stable/jme3-ios-3.1.0-stable.jar
     Required by:
         :sdk:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.426 secs

**Comment by MeFisto94** [comment]
Your Issue is now documented in the new readme: Essentially you have to build the engine on your own before you can build the sdk, since `jme3-jbullet` and the like aren't officially published to jCenter.
