### ISSUE TITLE
JmeTests projects should specify JDK 7 format, not JDK 6

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#114]
In the 3.1.0-stable-FINAL version of the SDK, new JmeTests projects are created with the source/binary format property set to "JDK 6". However, two of the tests (TestCloneSpatial and TestCloner in the jme3test.app package) use the diamond operator, which is a JDK 7 source feature. In addition, one of the tests (TestAnisotropicFilter in the jme3test.texture package) uses strings in switch, another JDK 7 source feature. These mismatches between the project and the source code cause builds of JmeTests to fail.

Over time, more JDK 7 features are likely to creep into the JmeTests source code, so the best long-term solution may be to change the project format to "JDK 7".

**Comment by grizeldi** [comment]
Oops, I fixed this some time ago for regular project template but apparently forgot about tests template.

**Comment by stephengold** [comment]
Thanks.
