### ISSUE TITLE
SDK does not work on OpenJDK

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/sdk#12]
_From @ghost on March 24, 2014 19:34_

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=411

_Copied from original issue: jMonkeyEngine/jmonkeyengine#45_

**Comment by erlend-sh** [comment]
_From @gouessej on August 11, 2014 13:37_

Is it still reproducible?

**Comment by erlend-sh** [comment]
_From @normen on August 11, 2014 13:38_

What if it was?

**Comment by erlend-sh** [comment]
_From @gouessej on August 11, 2014 14:7_

I use OpenJDK 1.7 update 65. Installing Oracle JDK under GNU Linux just for JMonkeyEngine is a bit... annoying. OpenJDK packages are provided with lots of distros wheras Oracle JDK is intended to work as is only on some of them.

**Comment by erlend-sh** [comment]
_From @normen on August 11, 2014 14:8_

The SDK comes with Oracles JDK... No need to install anything.

**Comment by MeFisto94** [comment]
```
darki@darkbox:~/Downloads$ ./jmonkeyplatform-linux-x64.sh 
Configuring the installer...
Searching for JVM on the system...
Preparing bundled JVM ...
Extracting installation data...
Running the installer wizard...
```
On `Ubuntu 14.04.3 LTS`
```
darki@darkbox:~/Downloads$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
```
Linux darkbox 3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:35:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
``

**Comment by MeFisto94** [comment]
```
darki@darkbox:~/Downloads$ ./jmonkeyplatform-linux-x64.sh 
Configuring the installer...
Searching for JVM on the system...
Preparing bundled JVM ...
Extracting installation data...
Running the installer wizard...
```
On `Ubuntu 14.04.3 LTS`
```
darki@darkbox:~/Downloads$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
```
darki@darkbox:~/Downloads$ uname -a
Linux darkbox 3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:35:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

Long Story Short: Even on that pretty ancient OpenJDK Box it worked. As such I will close this now.  

If you experience Problems, then the installer prefers the internal jre over the bundled one (which shouldn't be the case since we try to keep up with oracle's releases).
As such you can try to simply remove the openJDK for the time of the installation.
