### ISSUE TITLE
Error on converting models

### ISSUE THREAD

**Issue by Misat11** [jMonkeyEngine/sdk#122]
Hi,
I recently started working with JMonkeyEngine and I need help. When you try to convert the model into a blender j3o I get an error: 
WARNING [com.jme3.scene.plugins.blender.meshes.Face]: Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Woman_1:Female_generic, vertices.size()=10827]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.

After this message JMonkeyEngine SDK freeze.

I have a model generated by MakeHuman because with Blender I meet for the first time ever :)
My model: https://www.dropbox.com/s/72fmdzbl1dqflh0/womanmodel.blend?dl=0

MakeHuman 1.1.1
Blender 2.78 (I'm not using Blender in sdk, because I'm not know this :smile:)

Running on jMonkeyEngine 3.1-stable
 * Branch: HEAD
 * Git Hash: af04bf9
 * Build Date: 2017-02-19
INFO [org.netbeans.core.netigso.Netigso]: bundle org.eclipse.osgi@3.9.1.v20140110-1610 started
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: no suitable found, using fallback.
INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
OpenGL Renderer Information
 * Vendor: Intel Open Source Technology Center
 * Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
 * OpenGL Version: 3.0 Mesa 12.0.6
 * GLSL Version: 1.30
 * Profile: Compatibility
WARNING [com.jme3.renderer.opengl.GLRenderer]: Driver claims that default framebuffer is not sRGB capable. Enabling anyway.
Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency

Do you know what I'm doing wrong ??

Sorry for my bad English, I'm from Czech

**Comment by Ali-RS** [comment]
> Please apply triangulation modifier in blender as a workaround and load again!
You can use blender **[Triangulate Modifier](https://docs.blender.org/manual/en/dev/modeling/modifiers/generate/triangulate.html#triangulate-modifier)** to triangulate your mesh before export.

**Comment by Misat11** [comment]
Thanks, but something not loaded properly. My model is transparent and some textures is broken.

**Comment by Ali-RS** [comment]
> My model is transparent

Uncheck transparency in blender material tab 

https://jmonkeyengine.github.io/wiki/jme3/external/blender-material-1.png

Please see [wiki](https://jmonkeyengine.github.io/wiki/jme3.html#documentation-for-intermediate-users) page, you can find more blender related tutorials at **Animations and Scenes** section.

**Comment by Misat11** [comment]
After unchecked transparency no change

**Comment by Ali-RS** [comment]
hmm... Can you provide an screen-shot of your mode in jme ?

**Comment by Misat11** [comment]
yes, wait few minutes

**Comment by Misat11** [comment]
Here is a model after import into sdk (the only thing that has changed here after importing is the kind of light)

![snimek obrazovky porizeny 06 04 2017 15 12 09](https://cloud.githubusercontent.com/assets/20199703/24755741/9ad1a26c-1adb-11e7-85d7-6ce08b9892b2.png)

**Comment by Ali-RS** [comment]
I tested your model and it is not transparent in my case...  make sure to put alpha to 1 then uncheck the transparency for ALL materials.

**Comment by Misat11** [comment]
oh, I've forgotten a few materials (but Eyebrow001 and Eyelashes04 do not look very nice)

**Comment by MeFisto94** [comment]
So manually triangulating solved the problem for you and you could load it?
Because I am usually getting those messages as warning rather than a critical error, however there is another issue where we also discovered a freeze of the SDK possibly related to that.

The Problem here is that the importer is part of the engine however the maintainer is inactive.
There is, however, a clever way to import models more easily: Using XBUF. It is a Blender plugin which exports the model in a better format than .blend, would use blenders triangulation automatically and such things.

Since the SDK is able to read xbuf files you can just right click on them to create a j3o out of them. Just have a look at hub.jmonkeyengine.org and search for xbuf (or search for `xbuf` on github to find them project).

**Comment by Misat11** [comment]
its working, but materials not imported
