### ISSUE TITLE
hub.jmonkeyengine.org is getting 502 bad gateway error

### ISSUE THREAD

**Issue by DustinMerrell** [jMonkeyEngine/sdk#127]
I have been unable to access the https://hub.jmonkeyengine.org/ site for several days due to a 502 bad gateway error. Does anyone have any update on the site?

**Comment by EpicestGamer** [comment]
I've been getting that too, their servers may be down, as when I go to
http://jmonkeyengine.org chrome warns me of a bad security signature, as
it's being rerouted through github.

**Comment by JESTERRRRRR** [comment]
In case you didn't see it, more discussion here

https://github.com/jMonkeyEngine/jmonkeyengine/issues/653

**Comment by grizeldi** [comment]
It's back now

**Comment by grizeldi** [comment]
Uhh @MeFisto94 close this maybe?

**Comment by normen** [comment]
Who is dumb enough to report a website issue in a code issue tracker?
