### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by bonber** [jMonkeyEngine/sdk#131]
Configuring the installer...
When i try to install with $sudo ./jmonkeyplatform-linux-x64.sh i give the next error:

Searching for JVM on the system...
Preparing bundled JVM ...
Extracting installation data...
Running the installer wizard...
No protocol specified

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

**Comment by pspeed42** [comment]
Trouble shooting questions should be done on the forum.

**Comment by bonber** [comment]
Where is? i cant find it
