### ISSUE TITLE
[Scene Composer] Everything going black when enabling wireframe mode with filters enabled

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#132]
So this is my scene. Notice that I have SSAO and Bloom (on objects mode) filters enabled.
![screenshot from 2017-07-10 14-58-46](https://user-images.githubusercontent.com/13003371/28019191-5cbd2678-6580-11e7-8372-27cc0ff54432.png)
Enabling wireframe mode gets me this
![screenshot from 2017-07-10 15-00-13](https://user-images.githubusercontent.com/13003371/28019226-7dc2f578-6580-11e7-9c9a-8769fc3ffad8.png)
Turning off SSAO but leaving bloom produces exactly the same result.
Turning off bloom but leaving SSAO produces this
![screenshot from 2017-07-10 15-01-56](https://user-images.githubusercontent.com/13003371/28019284-be44f858-6580-11e7-9c71-601a2d55e57d.png)
Finally disabling both filters produces the expected result. So does disabling all filters with the eye icon next to the wireframe one.
![screenshot from 2017-07-10 15-02-24](https://user-images.githubusercontent.com/13003371/28019322-df195efc-6580-11e7-9e22-29dc213c508c.png)

I'd say the best way to fix this would be to just disable all filters automatically when wireframe mode is enabled and re-enable them again when you disable the wireframe mode.

**Comment by grizeldi** [comment]
Not to open another issue, when making screenshots for this issue, sdk produced a popup saying `unsupported key:154` every time I pressed printscreen button.

**Comment by normen** [comment]
Yeah, thats how a wireframe with a filter looks.
