### ISSUE TITLE
[Scene Composer] Unable to add/set collision shape

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#134]
Scene composer *supposedly* supports physics. There are start and stop buttons for physics and even an add collision shape button. All of them don't seem to do anything.
Also when you add a RigidBodyControl to a spatial in scene composer, there is no way to set the collision shape. It says something along the lines of "Property editor not found". Would it really be so hard to at least make a list of common collision shapes?

**Comment by normen** [comment]
"Common collision shapes"? Anyway, you can create collision shapes by selecting a geometry or node and creating a collision shape based on their meshes. This works fine and as you didn't specify any steps to reproduce or errors I'll close this issue.
