### ISSUE TITLE
Add slider to customize scene editor draw range

### ISSUE THREAD

**Issue by Antonystar** [jMonkeyEngine/sdk#138]
Default draw range in Scene Editor sometimes is too small so it will be good to add option that allows to customize draw range or change default draw range to 20000f+ if slider is not possible.

**Comment by MeFisto94** [comment]
Here you are ;) I still wonder what you do, that the default of 1000 is too low though :D 
If you have something like a mega-file for the whole scene consider splitting it up for multiple reasons.

Thanks again for reporting :)
