### ISSUE TITLE
Dicussion: Bundled JDKs

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#150]
So as it turns out we have the scripts to download the JDK for all 5 platforms (linux, windows and mac), however it is only used for Mac so far.

```
The existing JDK item is only used on MacOSX! On other platforms the jdk that is
bundled with the installer is used instead.
```

So I'm not sure what to do. We could ditch the other JDK downloads (at least that's what I'll do as a short term solution, to safe space etc) or use the downloaded JDKs as bundle (But I'm note sure how to do this exactly). This would give us more control over the used JDKs, I'm not sure how easy/problematic it is to select JDKs in Netbeans though.

I think you can just install any JDK on your System and tell it to use that, which means it's not necessary to bundle one.

@normen Can you maybe give any insight on why the JDK was required on Mac OS in the first place?

**Comment by normen** [comment]
No you're getting that wrong. The JDK is packaged for all platforms, only on OS it has to be a special installer item instead of a "bundled JDK", which works on all other platforms. This is (was?) a quirk in the NBI installer.

**Comment by MeFisto94** [comment]
Ah okay perfect, thanks for that insight!
I've now changed the "platforms" property so it should only require jdk-macosx.zip on MacOS Builds (which is important because due to travis constraints we have to build separately per platform).
Let's hope that this doesn't break anything, but since that installer item is only referring to jdk-macosx.zip, I guess it has just been overlooked and wont break the other jdks.
