### ISSUE TITLE
Does not launch on Mac OS

### ISSUE THREAD

**Issue by jsroadfood** [jMonkeyEngine/sdk#157]
I have a MacBook Pro running OSX 10.12.6. I downloaded jMonkeyEngine v3.2.0-stable-sdk1, the installer finished with no errors, and there is a jmonkeyplatform.app in my Applications folder. But when I double-click on it, nothing happens, the app does not launch. I've checked the system console and there does not appear to be anything in there.

Does anyone have any suggestions?

**Comment by pspeed42** [comment]
Ask trouble shooting questions on the forum where it will get waaaay more eyes.
