### ISSUE TITLE
Material Editor doesn't support file paths that contain spaces

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#161]
As title says, the material editor fails to load any textures that contain a space in their path.

**Comment by o-oualid** [comment]
this probably can be fixed by adding the source between " "
Example: "/Textures/old brick/diffuse.png"

**Comment by MeFisto94** [comment]
Can you maybe elaborate on that if you remember that? What does not work? Selecting the Texture in the File Chooser? Opening a Material which has previously been generated with a Texture?

**Comment by grizeldi** [comment]
IIRC if you try to load a texture with spaces, it justs splits it at the
space and uses the first part. Not sure if it happens after you select it
as a texture or after you try to reload such material. Will have to re-test.

tor., 27. nov. 2018 11.01 je oseba MeFisto94 <notifications@github.com>
napisala:

**Comment by o-oualid** [comment]
this happens when you save the material, a similar bug is present in JMB.
and like I said if you edit the material (material.j3m) and put the textures paths between 2 " " the material will load normally.
