### ISSUE TITLE
i can't download netbeans platform base

### ISSUE THREAD

**Issue by ejamshidiasl** [jMonkeyEngine/sdk#165]
in windows and with cmd i did "./gradlew buildSdk" and some files downloaded but our country is banned and gradle can't download "netbeans platform base".now i need url of "netbeans platform base" to download this from browser.please help me.

**Comment by MeFisto94** [comment]
The code is here:
https://github.com/jMonkeyEngine/sdk/blob/master/gradle.properties#L28
(currently http://download.netbeans.org/netbeans/8.2/final/zip/netbeans-8.2-201609300101-javase.zip)
However if you only want to use the SDK you should also be able to download a prebuilt version :slightly_smiling_face:
