### ISSUE TITLE
Error in Gradle Building

### ISSUE THREAD

**Issue by mikrokode** [jMonkeyEngine/sdk#171]
I am facing this error when building the sdk with gradle.bat in cmd. May I know how to solve it.

Downloading NetBeans Platform base, this only has to be done once..
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_6t9awmqdqvmygzumonci7nld8.run(C:\Users\kiantat.wong\Documents\NetBeansProjects\sdk\build.gradle:129)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\kiantat.wong\Documents\NetBeansProjects\sdk\build.gradle' line: 346

* What went wrong:
A problem occurred evaluating root project 'sdk'.
> Could not resolve all files for configuration ':optlibs'.
   > Could not resolve org.jmonkeyengine:jme3-jbullet:3.3.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.jmonkeyengine:jme3-jbullet:3.3.0-SNAPSHOT.
         > Could not parse POM C:\Users\kiantat.wong\.m2\repository\org\jmonkeyengine\jme3-jbullet\3.3.0-SNAPSHOT\jme3-jbullet-3.3.0-SNAPSHOT.pom
            > Unable to resolve version for dependency 'jbullet:jbullet:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 13s

**Comment by grizeldi** [comment]
Did you run build_engine.sh and fix_engine.sh? Those are required to properly install jbullet into your local maven repo.

**Comment by mikrokode** [comment]
Can you show me the way to install jBullet into local maven repo?

**Comment by grizeldi** [comment]
https://github.com/jMonkeyEngine/sdk#building-the-sdk
Especially the part under "**NOTE:**" section.
