### ISSUE TITLE
Fix version.gradle

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#178]
Currently version.gradle is parsing old style versions (`3.1` and `3.1-alpha2`) but not our newer naming scheme `v3.2.1-stable-sdk3` or `v3.2.1-alpha2-sdk4`.
The first part of the parsing is trivial and thus Contributions are Welcome. Do you know how to parse a string (String#split and String#substring), then you're qualified.

A more complicated question is that unlike earlier, we can't tell if we're stable or not just by the version. Actually the SDK has stopped differentiating between stable and dev, which is a problem here because this information was used for two update centers (nightly and master) back in the days `updates.jmonkeyengine.org` was active. On the other hand we have a more precise description of engine versions

**Comment by grizeldi** [comment]
Does it matter if it's stable or not though? JME is usually stable enough when built straight from master, so I really don't see an issue with not differentiating stable and unstable versions, since there's rarely any work done on the SDK that just breaks everything.

**Comment by MeFisto94** [comment]
Well yeah, I also believe that the SDK can be considered unstable every time :P Or put the other way around: Don't use the SDK if you don't secure your code and assets in a git/svn anyway.

It was relevant when there were two update channels, one brought the changes from master every night so you could have the updates very promptly

**Comment by MeFisto94** [comment]
This issue is solved with plenty of commits regarding this problem and also the gradle composite builds make the related problems obsolete (we only need to extract the correct engine version)
