### ISSUE TITLE
Upgrade the Plugins to be downloadable

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#18]
If you try to find any jme-plugin under 3.1 (e.g. jme3-ai) those packages don't appear in the dialog.
The reason is that they are under 3.0 in http://updates.jmonkeyengine.org and have to be copied and maybe modified for the new version.

**Comment by grizeldi** [comment]
I doubt we can fix that. Someone from the core team will have to copy that over...

**Comment by MeFisto94** [comment]
Yeah but they'll do that once we have clear instructions on what to do.
Actually we should even re-compile those plugins (there is a jmonkeyengine-contributions repo) and upgrade them and then simply pass them the binaries.

**Comment by MeFisto94** [comment]
Closing as currently we don't host plugins anymore
