### ISSUE TITLE
Get Rid of BeansBinding Library

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#181]
This affects the `NewGeometrySettingsTopComponent` and the `ConverterVector3f_String` classes. Since there is already code for properties to convert Vector3f and String, we could refactor this into a utility class.

The reason is that Netbeans 9.0 got rid of the library due to licensing issues (I hate that...)
https://issues.apache.org/jira/browse/NETBEANS-172
https://github.com/apache/incubator-netbeans/pull/300

Feel free to give it a try

**Comment by MeFisto94** [comment]
So this is a more complicated issue than just removing a library and changing a class.
Replacing the BeansBinding is a bit more complex and especially yields a Design Issue.

Currently there is the "NewGeometrySettingsTopComponent" Window, which is available by Window->... which defines how a Geometry, created like `New -> Primitive -> Sphere` (in SceneExplorer) is created. For a Sphere, there is a radius, a sample count to define etc, a color to set. A Mesh also has a Name, Boxes have their extent.

When using New Primitive, these values are drawn from the New Geometry Settings Window, which no one knew or would expect to be there. I can see the benefit of having a faster method especially when placing many spheres, where a popup would be annoying.

So the chances are:
  1. Keep it like it is and rework the BeansBindings
  2. Provide a Popup every time a Primitive is created. The Popup can be specific to the Primitive but popups are annoying if you are very fast
  3. Make Mesh Creation Settings Property aware. This is difficult because we just have a `Mesh` instance and would have to guess if it's a Sphere. And then also re-instantiate the mesh everytime this is changed (imagine someone using a `Spinner` and gradually increasing the sample count. Could make it laggy)

**Comment by grizeldi** [comment]
I'd go for #2. If you need to place a lot of the same primitives you might as well go for copy paste once you added the first one.

**Comment by MeFisto94** [comment]
Finally closed with 97bf29589264c28887b855de76f6a4011526c940
