### ISSUE TITLE
Add GLTF and other assets to the SDK's default exclude list

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#190]
https://hub.jmonkeyengine.org/t/gltf-files-and-assets/41806/3

**Comment by grizeldi** [comment]
Not sure why this didn't autoclose with my PR, but we can probably close it.

**Comment by MeFisto94** [comment]
Probably because it only contained `Fixes #190` in the title, not in the actual commit :man_shrugging:
