### ISSUE TITLE
jme3-lwjgl3 library not included in the SDK

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/sdk#193]
The Ant Library Manager dialog (menu bar -> Tools -> Libraries) shows that most of the official JME libraries are available (including `jme3-jbullet` and `jme3-lwjgl`) but not `jme3-lwjgl3`. This omission occurred in both `v3.2.3-stable-sdk1` and `v3.2.2-stable-sdk1`.

Please add the `jme3-lwjgl3` library to the next SDK release.

**Comment by grizeldi** [comment]
Can second this, I've been unsucessfully looking for it a couple times already.

**Comment by rkraneis** [comment]
Unfortunately still an issue even in 3.3.0-beta1.

**Comment by MeFisto94** [comment]
I wonder if this is still relevant now that we will support gradle, but given that people might need some time to transition, we probably should.

**Comment by stephengold** [comment]
Thank you.
