### ISSUE TITLE
Deleting Files doesn't work

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#197]
For this issue I guess the best we can do is see if this is fixed with more recent Netbeans Versions.

**Comment by grizeldi** [comment]
Wait what? I'm pretty sure this does work? Anything more specific or simply that deleting any type of file doesn't do anything?

**Comment by MeFisto94** [comment]
Deleting a .j3o under my assets "succeeds" but nothing happens after and the file remains there.
I have a j3odata and the xbuf original in place there as well, so maybe something is holding a lock on that file somehow. Also this happens using the Projects Tab. Not sure whether it works using the Files tab

**Comment by MeFisto94** [comment]
Things like:
```
File /TestFloor1.j3o@f6255155:3769f7e3[invalid] deleted, remove!
```
and
```
TestFloor1 listening for external changes on TestFloor1.xbuf@d0d2f7ec:6599ed76
External file TestFloor1.xbuf@d0d2f7ec:6599ed76[invalid] for TestFloor1 deleted!
Remove file change listener for deleted object on TestFloor1
```

are logged, so it looks like in theory the deletion worked, but it isn't executed. This happens for both the projects window and the files window.

Could this be a Unix (Linux and Mac) only problem?

**Comment by neph1** [comment]
Doesn't occur anymore.
