### ISSUE TITLE
Fix many Java > 8 deprecation warnings

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#198]
With Netbeans 9/11, we are on java 10 for most modules (java 6 got deprecated, and there is no reason to use a lower version than what is supported/required). 

Most of these issues are `new Integer(i)` or `new Float(f)` to box, instead one should use Autoboxing or a cast where necessary.

In theory one should compile a list of these warnings and then we can track progress here, but since those are so many, just fix a few warnings and tag your commit message as `towards #<issue>`, at best do it module-wise

**Comment by tonihele** [comment]
Sorry, I missed this issue. This was done in the cleanups.
https://github.com/jMonkeyEngine/sdk/pull/219
https://github.com/jMonkeyEngine/sdk/pull/216

**Comment by tonihele** [comment]
This one remains: https://github.com/jMonkeyEngine/sdk/issues/217

**Comment by MeFisto94** [comment]
Closing, as #217 is a new issue
