### ISSUE TITLE
GLTF: Keep Userdata

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#202]
jme's userData needs custom handling when importing gltf

**Comment by pspeed42** [comment]
Though note as a work-around, I believe JmeConvert already handles this and can be automated.  (SDK can't be automated.)

**Comment by pspeed42** [comment]
Just need to do what this class does in JMEC:
https://github.com/Simsilica/JmeConvert/blob/master/src/main/java/com/simsilica/jmec/gltf/GltfExtrasLoader.java
