### ISSUE TITLE
Add Contextmenu for .fbx files

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#21]
Simple Issue:
We have that great .fbx->.j3o or .fbx -> .blend functionality nobody knows off because it's not exposed enough.

That and we need a double click action aswell.

**Comment by normen** [comment]
fbx via blender works fine by double-clicking or by using the model importer

**Comment by MeFisto94** [comment]
I just check it again: The "Open" is greyed out and as such the double click doesn't work.
Also it's more intuitive to have it consistent to blender files.

But the Model Importer works anyway.

**Comment by normen** [comment]
Then you broke somrthing. This takes care for the file type support: https://github.com/jMonkeyEngine/jmonkeyengine/blob/3.0/sdk/jme3-blender/src/com/jme3/gde/blender/filetypes/BlenderFbxDataObject.java

**Comment by MeFisto94** [comment]
I think it was related to that commented out line registerEditor().
At the current state "open" was greyed out and that's what's called when you double click anyway.

Uncommenting that line however would lead to displaying that file in the text editor.
I now did what was recommended for overriding the default OpenAction: Override AssetDataNode's getPreferedAction() to return own of the actions.

**Comment by normen** [comment]
Theres no separate action needed

**Comment by MeFisto94** [comment]
I just double-checked it. At it's previous state, loadAsset isn't called by double-clicking and open is grey.
I also checked: There is no call to loadAsset other than the one I implemented in that action.

Well at least it works now, one more Action doesn't really harm.
