### ISSUE TITLE
Blender 2.8 Support

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#222]
So this should be more of a milestone, but:
We integrate Blender on several ways, we need to ensure that that still works.
One thing is the automatic scripts (e.g. when trying to import an fbx file, we invoke blender's fbx importer). This could even be improved to not use the Blend Importer but convert fbx -> blend -> gltf.

Also BlenderLoader won't work.
We also need to ensure that the OgreLoader Plugin has a 2.8 compatible variant.

**Comment by grizeldi** [comment]
Ogre exporter for Blender 2.8 is paid for iirc.

**Comment by tonihele** [comment]
We dropped Blender. Load FBX through jME as well.

Maybe in the future we could have @stephengold MonkeyWrench or optionally if Blender is detected in user's system, use it to convert plethora of formats to GLTF. But not a fan of bundling Blender anymore.

Closing this.
