### ISSUE TITLE
LWJGL2 crashing on Ubuntu's JVM

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#226]
According to @jayfella [this](https://hub.jmonkeyengine.org/t/solved-jme-does-not-work-at-all-on-modern-java-due-to-a-regression/42112/22) the following error occurs starting 11.0.5 and lwjgl2 [on linux] :
```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```
That's the exact issue @grizeldi also had when trying out the new SDK Version locally.

**Comment by grizeldi** [comment]
Upgrading to lwjgl3 for linux only sounds stupid to me. If we do the upgrade, I assume we'd do it for all the systems, right?

**Comment by MeFisto94** [comment]
Yes, of course.

In fact, I might have done a fault in declaring this for "Linux". I was
lead to the conclusion as you tried that on linux and the error message
contains "dl",
where dlopen is the syscall on linux to load a dynamic linked library,
but after all this could only be the abstractional code from the JVM and
thus affect all platforms.

@jayfella actually complained even more about 11.0.5 leading to trouble
for him, so the easiest is a downgrade and then iron out lwjgl3 on the
engine and when all of this is done, a new LTS of Java is probably
already released.

Fun-Fact: Thanks to upgrading the source level, I can't even build the
SDK on my local machine anymore, as it's running KUbuntu 18.04 LTS with
Java 8 :D

**Comment by MeFisto94** [comment]
Short info:
I've done quite some investigations upstream and it looks like the issue is a faulty `libjawt.so` from the Ubuntu distributed JDK.

Using AdoptOpenJDK or AdoptOpenJDK Upstream (i.e. the original OracleJDK built by Redhat) works and according to my digging it seems that even Debian's JDK still works, so you could swap out .so's or better install AdoptOpenJDK and adjust `JAVA_HOME` (which I also need to do anyway, as java 8 is still my default :D).

In theory the SDK Installer should use the bundled adoptopenjdk, but you never know if it prefers locally installed jdks first.

**Comment by MeFisto94** [comment]
Closing this as it's tracked at the Engine and the SDK Installer come bundled with AdoptOpenJDK.
In case someone has this issue, comment here. Most likely the jmonkeyplatform.conf needs to be modified, which is our issue then.

Otherwise you can also change `JAVA_HOME` to point to the jdk subfolder of the installed SDK.

NOTE: The Platform Independent ZIP WILL show this behavior on Ubuntu and we don't "support" that. If you use that zip, take care of having an appropriate jdk linked.
