### ISSUE TITLE
Fix dependencies regression from 4221ce9

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#231]
So, in 4221ce9b9f231a6c4e45f29a0c5393245dfa5ee0 we removed mavenLocal and went on to use a composite build.

This means that the jme3-project-libs.nbm's are empty and the jars get added to `ext/`
 - This is bad for auto updates
 - This breaks the IDE functionality, as you cannot depend on engine jars anymore.

The latter makes this rather critical. I have no clue how to properly solve that though, as it usually involves us manually taking the jars and influencing the ant/netbeans build and I was glad things "worked" so easily and properly in 4221ce9b9f231a6c4e45f29a0c5393245dfa5ee0

**Comment by MeFisto94** [comment]
So, this issue is probably a bit more difficult to fix, especially since it involves finding out where the problem lies/debugging the gradle and ant builds.

## How this issue affects users
The wiki instructs users to add the `jme3-desktop` library to the project.
This library is not found.
None of the jme related libraries are found, in fact.

## Workaround
The user has to manually create libraries pointing to the files in `jmonkeyplatform\libs\*.jar`

I'm sorry for the impact this may have, especially for new users. Fortunately the workaround is really easy, so please help to spread awareness by pointing users experiencing this to that issue.
Contributions to fix this issue are more than welcome!

**Comment by MeFisto94** [comment]
Note that I just got a report from a user on Mac OS X where this problem didn't happen.
It could be that my environment was just flawed for some reason, I will double check.

If it looks like this, you don't need the Work Around and it works for you.
Please comment here if that's the case
![img](https://cdn.discordapp.com/attachments/675038991678177308/676545959274217532/Screenshot_2020-02-10_at_22.50.46.png)

If however these libraries are marked in red because the jars couldn't be found, you have to look them up in `jmonkeyplatform\libs\*.jar`

**Comment by MeFisto94** [comment]
It seems this was just a temporary issue with my builds as there didn't seem to be any complaints.
Did anyone experience this issue?

**Comment by hangingman** [comment]
@MeFisto94 Hi,
I'm facing build issue on master branch. 
Is there any procedure to build SDK properly ? I already refereed README etc. 
I executed script according to documents but gradle error occurred like "optlibs" can't be resolved.
I commented because it seems this ticket might related with the build error.

**Comment by MeFisto94** [comment]
Is the optlib you are missing, by any chance, jbullet?
If so, it's the consequence of https://github.com/jMonkeyEngine/jmonkeyengine/pull/1352

The _problem_ is that the engine branch used should be v3.3 (you can easily do that manually), because master isn't upgraded to "3.4" yet, because we still didn't cut a v3.3 release.

Our master always picks the engine master, but when doing a release, it extracts the branch out of the version. Basically we'd need a 3.3 branch where we force-specify the engine version 3.3. 

I didn't do that yet, as I didn't want to cherry-pick commits back and forth, as we won't have any non-3.3 commits in the near future.

**Comment by hangingman** [comment]
@MeFisto94 I have understood following point.

> The problem is that the engine branch used should be v3.3

But, my build (I'm using Windows environment) is still failing because of "optlibs" can't be resolved.
It seems my own environment's error messages are similar with CI environment error messages.
https://travis-ci.org/github/jMonkeyEngine/sdk/jobs/692909414

```bash
* What went wrong:
A problem occurred evaluating root project 'sdk'.
> Could not resolve all files for configuration ':optlibs'.
   > Could not find org.jmonkeyengine:jme3-jogl:.
     Searched in the following locations:
       - file:/home/travis/build/jMonkeyEngine/sdk/lib/jme3-jogl.jar
     Required by:
         project :
```

In my wild guess, it's caused by gradle dependencies don't have version string.
Or, we should prepare jar files don't have version string like `jme3-jogl.jar` for build instead of `jme3-jogl-xxx-SNAPSHOT.jar` ?

**Comment by MeFisto94** [comment]
Sorry, I linked the wrong PR: https://github.com/jMonkeyEngine/jmonkeyengine/pull/1339
The problem: JOGL got removed from the engine, but the SDK is searching for it.
The rest is still true, try to fix the engine version that is in ./engine by checking out a 3.3 version.
Maybe you can also remove `optlibs jogl`from the build.gradle for local testing

**Comment by jcrosby10** [comment]
I just installed SDK v3.3.0-beta1-sdk1 without this issue. I'm on Linux Mint and I used the jmonkeyplatform-linux-x64.sh file to install it.

**Comment by MeFisto94** [comment]
After investigating all, this issue is fixed, it's just that javadoc and sources don't work, see #283
