### ISSUE TITLE
Support .glb files directly

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#233]
Currently we support .gltf files, .gltf files with additional glb data files, but no import of .glb files directly.
Does the engine support this? If so it's simple to add.

**Comment by pspeed42** [comment]
Yes, the engine supports it.

**Comment by grizeldi** [comment]
I'm pretty sure .gltf with .glb data files combo doesn't exist. All the cases that I've seen use .gltf and .bin combo.

That aside, yes, .glb loading works fine in the engine, it's just a matter of creating a proper file type definition in netbeans.
