### ISSUE TITLE
Warning: GraalVM Debugging Support - Missing truffleapi

### ISSUE THREAD

**Issue by swiftech** [jMonkeyEngine/sdk#237]
Warning - could not install some modules: GraalVM Debugging Support - The module named org.netbeans.libs.truffleapi was needed and not found.

SDK v3.3.0-beta1-sdk1
macOS Catalina 10.15.3

**Comment by MeFisto94** [comment]
Thanks, good that we have an issue to track.
Can you try to get the "Graal VM Debugging Support" using Extras -> Plugins?
I guess we just have a packaging issue here. Actually we don't need GraalVM Debugging Support, but had it enabled and forgot "truffleapi"

**Comment by MeFisto94** [comment]
Fixed in https://github.com/jMonkeyEngine/sdk/commit/5be6123ca8f7f8ea4d57c23d52e61fe6713bb8e5
