### ISSUE TITLE
Add Core Sources to SDK nbproject

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#24]
When you try to debug something which calls core code you only see the jvm assembly.
I think we already download the source packages, we only need to link them into the netbeans project to be found by it.

**Comment by normen** [comment]
The library package normally contains the source and should link it. What sometimes doesn't work is going further, i.e. if you're browsing for example the jme3-jbullet source and click on a class that is in jme3-core.

**Comment by grizeldi** [comment]
Is this still the case? I can't reproduce it.

**Comment by MeFisto94** [comment]
I can't reproduce it either, maybe something was wrong with my setup back then, but at least it's solved
