### ISSUE TITLE
Re-Applying changes from gltf files broken

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#252]
See [here](https://hub.jmonkeyengine.org/t/solved-animation-not-working-in-sdk-scene-composer/42916) for context.

![img](https://jme-hub-cdn-jmonkeyengineor.netdna-ssl.com/uploads/default/original/4X/0/5/b/05bfb037a820d708da388e6ba928c9f37a37c9ca.png)

**Comment by MeFisto94** [comment]
The cause is that it tries to use 3.2 SkeletonControls instead of Armature.

**Comment by neph1** [comment]
Can this be closed?

**Comment by MeFisto94** [comment]
I am not sure, I haven't really experimented with all possible side effects of re-applying gltfs again.
Did you spot something in the context of #315 ?
If not, we can probably close it and re-open an issue if that's required :)
