### ISSUE TITLE
Include Gradle plugin installed as default and add the jME Gradle project template

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#255]
Include Gradle plugin installed as default and add the jME Gradle project template (I think the store or the jME documentation had this?). We would still have the ye olden Ant template. But also offer some modern bells & whistles. This would also a bit decouple the SDK from the engine. As the template allows even inexperienced user to use jME version they want.

**Comment by swiftech** [comment]
The Gradle or the Maven template is better than the  Ant template to me

**Comment by MeFisto94** [comment]
Using the Gradle Template would remove all the SDK Functionality from the User, to the point of being able to use the Gradle Template with another IDE.

So we first need to fix Gradle on the SDK (see the branch gradle-support, the commit message is pretty explainatory)

**Comment by swiftech** [comment]
I have tried the latest preview build for Gradle template, but I didn't find any Gradle things after creating a project by the BasicGame template. Did I miss something to enable this functionality?

**Comment by tonihele** [comment]
This issue is still open (not implemented). The preview should have Gradle plugin enabled by default. So you don't have to manually install it. The BasicGame template is still Ant template as far as I know. So either open an existing Gradle project or create new one, but no template available.

**Comment by MeFisto94** [comment]
Exactly, you need to open a "jme gradle project", that is a project with gradle which contains a subproject called `assets`.

There everything else should work: Asset Editing, Starting, Debugging.
The template will be more complicated as I am thinking about including Android and have it Android Studio compatible.

**Comment by tonihele** [comment]
This is implemented some time ago.
