### ISSUE TITLE
Possible Documentation Issue - (Building the SDK)

### ISSUE THREAD

**Issue by supertick** [jMonkeyEngine/sdk#292]
Hello,
I've followed the documentation as best as I can understand it.
So far most instructions work well, although now I'm a bit perplexed on the 
**If you want to debug the SDK inside an IDE:**
section, specifically:
`See above. You want to open the SDK as Netbeans Project from within Netbeans (you can use the nb in netbeans/) and you can then treat it as regular project with the difference that there are several subproject.
`
I can see no netbeans/ directory.  There is a nbproject directory, yet using a recent version of netbeans, and trying to import that project folder does not work.

disclaimer : I am primarily a eclipse user - netbeans is new to me, maven is also more familiar to me than gradle.  Following the instructions did work up to that point, but I'm hoping to run master of jmonkeyengin & jmonkeysdk in the debugger to look into the vr possibilities.
Any help is most welcome.
Thanks.
Sincerly,
supertick

**Comment by MeFisto94** [comment]
You might have to build the SDK once by invoking `(./)gradlew(.bat) buildSdk` (choose the ()s depending on the OS).
This will download netbeans and also setup some more project structure. Using a regular netbeans install should however be able to import our project, if it doesn't show as Puzzle pieces in blue and orange maybe make sure to disable the gradle plugin/support.

Our problem is that we have a classical Netbeans project but also a gradle build and now that Netbeans has Gradle Support, it completely ignores the classical project.
