### ISSUE TITLE
SDK 3.3 com.jme3.scene.CenterQuad not reachable

### ISSUE THREAD

**Issue by Lagermeister** [jMonkeyEngine/sdk#299]
This class is not reachable in the SDK. The Javadocs (3.3 - 3.4) for the package com.jme3.scene lists all classes starting with "AssetLinkNode" - "VertexBuffer". All these class are available in the SKK and only the class "CenterQuad" is an exception.

**Comment by stephengold** [comment]
`CenterQuad` is part of the jme3-vr library. If you add the jme3-vr package to your project, you should have access to it.

For most purposes, I would recommend using a plain old `Quad` instead.
