### ISSUE TITLE
 I don’t know why I can’t install SDK after updating windows11 on my computer

### ISSUE THREAD

**Issue by ZhuYebai** [jMonkeyEngine/sdk#300]
![image](https://user-images.githubusercontent.com/76416678/134795935-5ecec706-4f6c-4848-bcf2-48ca14ea84a5.png)

**Comment by tonihele** [comment]
I'm fairly confident this is now resolved. I believe this is the issue: https://bugs.openjdk.org/browse/JDK-8274840. This is resolved in 11.0.13. We ship the new release with JDK 11.0.15. Feel free to reopen if this is still an issue.

JDK 16 says it is the first to support Windows 11 but I really suspect that they have now included the support to JDKs that are currently still supported.

The new release:
https://github.com/jMonkeyEngine/sdk/releases/tag/v3.4.1-stable-sdk1
