### ISSUE TITLE
MacOS : SDK installer v3.3.0-stable-sdk1 only works with JDK 11

### ISSUE THREAD

**Issue by marcelfalliere** [jMonkeyEngine/sdk#307]
Everything in the title.

Without it, there is either no error, a "Major/Minor error", or a missing classdef java/util/jar/Pack200

I've tried with different JDK versions,  JDK 11 is the only one that seems to be compatible with the sdk.

For a production ready software, being unable to even launch the installer is ... not nice, PR wise.

I think this requirement should be written in bold somewhere on the download page / website.

**Comment by peedeeboy** [comment]
I think this is related to the underlying Netbeans platform using Pack200 to compress Netbeans Modules (NBMs):https://issues.apache.org/jira/plugins/servlet/mobile#issue/NETBEANS-2842

Pack200 was removed from >= JDK14: https://openjdk.java.net/jeps/367

**Comment by MeFisto94** [comment]
@peedeeboy is completely right here in both cases.
I don't know if we can just skip pack200 going forward, but in theory this shouldn't matter, as we bundle our own JDK 11 that should be used.

So the problem seems to be that the Mac OS X Installer is not picking up that jdk.

**Comment by marcelfalliere** [comment]
JDK Management on Mac is a pain. I've tried a tool called jabba, one called jenv (with homebrew). Their are both Java Version Management tool. It used to work some years ago, now it doesn't. JAVA_HOME and PATH env variable are not picked up when it comes to Java.

The only way for me, even though I did not investigate this Java installation in much depth I must admit, was to go to Oracle.com and pick up JDK11.

I confirm the JDK bundled with the installer is not picked up at all.

If you want some test with a Mac, I can do that.

**Comment by MeFisto94** [comment]
Sure that would be awesome, I however probably can't guide you too far.
Inspecting the .app would be the first thing: It has to have some `Info.plist` with metadata and that pointing to some command that is executed, somewhere in `Contents`.

You can check those via `cd`'ing or right click open package contents, I believe.
There you can hopefully see a jvm and some command line flags that tell the installer to use it or something.
You should also be able to manually execute those commands then for the installer.

FWIW, going forward we will have to remove pack200 again and hope to still stay under 1GiB of size for the downloads

**Comment by MeFisto94** [comment]
Duplicates #297

**Comment by tonihele** [comment]
Closing as duplicate to #297
