### ISSUE TITLE
 SDK 3.1-pre-svn JME3 New BasicGame - template with older libraries

### ISSUE THREAD

**Issue by Dokthar** [jMonkeyEngine/sdk#31]
_From @slawekmikula on May 11, 2014_

Template BasicGame when creating with current HEAD SDK require older libraries: jme3 and jme3-libraries. Due to fact, that jme3 is split to many partial libraries it has to be updated to core library jme3-core and provide in simple readme in BasicGame method to add more specific libraries.

_Copied from original issue: jMonkeyEngine/jmonkeyengine#136_

**Comment by MeFisto94** [comment]
This seems fixed in the meantime.
The question is if we should remove jBullet in Favor of Bullet Native, though?
