### ISSUE TITLE
Upgrade to Netbeans 14

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#328]

**Comment by tonihele** [comment]
A side note, Netbeans will no longer have LTS releases. Netbeans 12 was the last of such.

For the SDK I think this means that we should just maybe get the latest NB for a SDK release.

**Comment by tonihele** [comment]
Which is 14 now :)

**Comment by tonihele** [comment]
Closed with https://github.com/jMonkeyEngine/sdk/pull/358
