### ISSUE TITLE
Mounted drives option when opening project

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#340]
This is a feature I've been wishing for for a long time, and possibly something more related to Netbeans than the SDK. It would be really nice if you got the option to choose between mounted drives when opening projects.

**Comment by tonihele** [comment]
You can re-check the issue now. Newest release is on NB 14 if this makes any difference.

**Comment by neph1** [comment]
I think it might be due to Netbeans not using the native open/save dialog. I see the behavior in some other applications too. It is what it is, I guess.
