### ISSUE TITLE
Update the Wiki about Library Changes

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#35]
So, #31 (or rather 970463a) introduced some changes:
> - We use JBullet instead of Bullet-Native
- We've removed Support for Runtime Loading of .blend files.
- We've removed NiftyGUI

So the first one won't be noticed and the second one might detect bad behavior (because a typical game won't need .blend loading and even for addons/mods you should prefer .j3o as there might be some necessary changes or the import fails).

The third one has to be changed in Hello_GUI or whatever we have.
There already is a Wiki-Page about Libraries, however it states on how to split the 3.0 "jme-libraries" into more fine-grained control.
Link that Page in the Hello_* Tutorials and deprecate that 3.0 stuff, but include how to add libraries (Nifty GUI) to your project.

I'll do it once the wiki is up again.

**Comment by grizeldi** [comment]
So jMonkey site is not down for just me... Do you know what's going on?

**Comment by MeFisto94** [comment]
BTW: There are pages for that (downforeveryoneorjustme).
https://twitter.com/jmonkeyengine/status/710377671440666624 <- this

**Comment by grizeldi** [comment]
Oh right. I tweeted to them yesterday but didn't check twitter yet. Thanks!

**Comment by MeFisto94** [comment]
Since I can't login atm would someone edit the [hello_phyiscs](http://wiki.jmonkeyengine.org/doku.php/jme3:beginner:hello_physics) just to state that we use the native compiled version of Bullet over jBullet and that you can still revert to jBullet if you experience bugs by simply Rightclicking the Project, going to Properties->Libraries and there removing Bullet-native but adding jBullet?
