### ISSUE TITLE
Splash Screen Always on Top (on Linux)

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#38]
So this is the Issue:
When you run the SDK, we usually ask for your Project Directory.
Since 8.1, Netbeans decided to make their Splash Screen pretty aggressive.
It's on top of File Explorers and doesn't disappear when you try to stop the SDK in Netbeans.
You have to kill the java process. Also see https://netbeans.org/bugzilla/show_bug.cgi?id=258236

As a Quick & Dirty workaround (since grabbing the window is unacceptable and simply pressing Enter/Escape sucks), I'll hide the splash until the path has been loaded and reopen the splash again.

However! I will keep this Issue open so we can remove the Workaround with 8.2 again.
The workaround introduces a "fatal warning", this is due to the fact that I didn't specify any special version of the core and as such, netbeans considers this a risk since the internal api might change any time. See here: http://wiki.netbeans.org/DevFaqImplementationDependency

This infact is no problem because the next breaking change hopefully fixes the Splash and if not, it's very unlikely that "getComponent" or "setRunning" will be removed at all..

**Comment by grizeldi** [comment]
Hmm? Like one week ago this didn't happen on my live usb ubuntu when building from source...

**Comment by MeFisto94** [comment]
Well trust me it was there :stuck_out_tongue: 
it at least happened on Kubuntu 14.04 and maybe you didn't have that because you've already closed that dialog once?

**Comment by grizeldi** [comment]
Sure I believe it was there ;) It might be true that it found settings of
my old sdk.

**Comment by MeFisto94** [comment]
Since the Netbeans Team have flagged the related issue as WONTFIX, I guess we will stick with that workaround forever. Fortunately it is an acceptable hack, though.
