### ISSUE TITLE
Look And Feel

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#397]
When replacing icons I've been playing around a bit with LaF to see how they look in different themes. I find FlatLaf Dark to be superior to DarkMonkey (which I figure is based on DarkMetal?) and it feels much more modern (or is it just very similar to IntelliJ/Android Studio?)
I thought I'd raise the question whether we can change LaF.

**Comment by neph1** [comment]
Not sure I agree with myself.

**Comment by peedeeboy** [comment]
FWIW, I think FlatLaf Dark LAF combined with DarkMonkey editor colours is a good balance of modern looking UI yet distinct from stock NB

**Comment by neph1** [comment]
I realized there was a discussion about LaF already: https://github.com/jMonkeyEngine/sdk/issues/286
Yes, I came to the same conclusion. Using FlatLaf colors seemed wrong, somehow.
