### ISSUE TITLE
Creating a new Gradle project doesn't name it expected way

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#407]
If I create a new Gradle project and name it TestProject, it will show up in projects as "GradleDesktopGameProject". Its path will be "TestProject/GradleDesktopGameProject"
After building it once, it says "BasicGradleGame" in the projects tab.

Expected: My project would be name "TestProject" in the projects tab.

**Comment by peedeeboy** [comment]
Is this true in the dev build of the SDK?  I templated the `settings.gradle` with FreeMarker, so the project name should go in there (it was previously hardcoded to `BasicGradleGame`) and thus should show correctly in the NB Project window...

**Comment by neph1** [comment]
I can't reproduce it in master. Perhaps I was confused and used an old version at the time.
