### ISSUE TITLE
Add higher resolution icons to the branding

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#413]
Currently we only supply icons 16x16, 32x32 and 48x48. These reside in branding\core\core.jar\org\netbeans\core\startup. Netbeans however has already for some time supported larger icons which we should of course supply.

We need icons for 256x256, 512x512 and 1024x1024. Note that these should be PNGs instead.
https://github.com/apache/netbeans/blob/master/platform/core.windows/src/org/netbeans/core/windows/view/ui/MainWindow.java#L509

I only found 256x256 icon. Where is the SVG source for the jMonkeyEngine icon?

This might affect issue: https://github.com/jMonkeyEngine/sdk/issues/303

**Comment by neph1** [comment]
If it is of interest, I used this tool: https://vectorizer.com/ to convert the stylized "jumping jaime" png to svg to use as an icon. I simplified it considerably, although it originally looked OK at high resolutions too.
I tried it with Jaime's face too, but it was not very successful due to the details. But IMO, we could switch to the stylized logo. It looks better (again, IMHO).

**Comment by tonihele** [comment]
I would guess that this is the official logo of jMonkeyEngine. As of such, I wouldn't touch it. Branding issues are important and delicate stuff. I went with upscales of the original (@riccardobl ) magically upscaled them (Discord), no questions asked. They look crisp.

Netbeans shows in the branding its own logo when these higher resolution icons are not available. That still doesn't prove however that this would fix https://github.com/jMonkeyEngine/sdk/issues/303.

**Comment by peedeeboy** [comment]
> Where is the SVG source for the jMonkeyEngine icon?

> I tried it with Jaime's face too, but it was not very successful due to the details.

I made one (16px but SVG so you can scale it up / down) using Adobe for a little side project I've been working on for a JME starter (e.g. setup a new project) plugin for IntelliJ.

Looks good at smaller sizes 👍 

![jmeNode](https://user-images.githubusercontent.com/44434629/199296251-6c0e8487-26a9-4c14-8212-65c42a9d0dc2.svg)

**Comment by neph1** [comment]
Cool, I've added your logo to the icon list and replaced the usage of the silhouette (but when is that supposed to be used? A question for another thread, I suppose)

**Comment by neph1** [comment]
Seems it doesn't fix #303, at least not as it's perceived on my machine. :(
But I don't know if mine is the "usual" use-case.

**Comment by tonihele** [comment]
> Seems it doesn't fix #303, at least not as it's perceived on my machine. :( But I don't know if mine is the "usual" use-case.

Damn :( thanks for trying!

**Comment by riccardobl** [comment]
> magically upscaled them (Discord), no questions asked

I upscaled it with SwinIR 🫡
