### ISSUE TITLE
Importing model face triangulation error

### ISSUE THREAD

**Issue by jojoofu** [jMonkeyEngine/sdk#44]
Here is the error description taken from the SDK. 

> Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=Default, vertices.size()=201]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.
> The texture Kd has linear color space, but the material parameter DiffuseMap specifies no color space requirement, this may lead to unexpected behavior.
> Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().

I used the same models in JME 3.0 with no problems. When I try to load them into 3.1 they come out a bloody mess flipped faces and polygons all over the place. I even loaded them into blender 2.76 then tried importing with the same result.

**Comment by MeFisto94** [comment]
@jmekaelthas  is this fixed by jMonkeyEngine/jmonkeyengine@48b3f1a ? 
If not it would be nice if you could upload said model @jojoofu 

Also this usually rather fits into the main repository.

**Comment by jojoofu** [comment]
Okay here is the file. Feel free to move this thread as I'm not to sure where to place them.

[mesh_oldhut.zip](https://github.com/jMonkeyEngine/sdk/files/203276/mesh_oldhut.zip)

**Comment by jojoofu** [comment]
This issue seems to be resolved by using 3.1 alpha 4.

**Comment by MeFisto94** [comment]
Well I'm waiting for Kaelthas' Reply and then Close the Issue.
I don't know if there was a triangulation change between ~alpha2-alpha4 but when it works now, we're all happy :)

**Comment by jmekaelthas** [comment]
Hi,
I have loaded the model and it looked OK. But I have seen some triangulation problems in the log. Fortunately such errors during triangulation are caught and then the most simple triangulation algorithm is applied. Thanks to this most of the models will look fine even if there are some problems.

Because I am working on a new feature for blender importer at the moment, which forced me to improve triangulation algorithm, I think we can close this issue:)
I will check the model while I am done and I hope even the warnings will vanish.

**Comment by stephengold** [comment]
I'm seeing a similar issue in 3.1beta2 (with a different Blender model). Log messages like so:

Loading animations that will be later applied to scene features.
Loading model's textures.
Loading model's textures.
Errors occured during face triangulation: Unable to find two closest vertices while triangulating face in mesh: TemporalMesh [name=arcade, vertices.size()=32]Please apply triangulation modifier in blender as a workaround and load again!. The face will be triangulated with the most direct algorithm, but the results might not be identical to blender.

Did the improved triangulation algorithm ever get implemented? Should I just ignore these warnings?

**Comment by empirephoenix** [comment]
Not sure, but what happens if you actually do the triangulation in blender? does the error persist anyway then?

**Comment by stephengold** [comment]
Good question. After I used Blender to triangulate all the mesh faces, the warning disappeared. So I guess there's a workaround for now.
