### ISSUE TITLE
Material Editor preview improvements

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#453]
From @grizeldi 's wishlist:

_"Preview could really do with being able to turn the preview object around. Since it’s currently static, it’s rather useless for anything that involves lighting or normal manipulation. While I’m writing down my wishlist, a way to import a custom model for preview would be awesome as well."_

Loading a custom model may be useful in some cases, but the user could just use the scene viewer instead. Same goes for moving around.
I'm going to take some liberties with this request and suggest implementing being able to select a more "complex" (predefined) model in addition to the primitives. This would go as an extra button beneath the others.

**Comment by grizeldi** [comment]
While not exactly what I had in mind, at least the famous teapot or Suzanne would be a good start for previewing some general more complex effects.
I primarily meant it as a way to preview materials that only make sense on a certain 3D model, but as you pointed out, scene composer can get the job done just fine for that. I'd have to check if shader refreshing works properly there though, it's been a while and I vaguely remember there being a reason why I didn't end up using scene composer for this.

**Comment by neph1** [comment]
At least material refreshing works, but I don't think matdefs would trigger the update since it's tied to the material editor atm. That's part of the other ticket.
