### ISSUE TITLE
Editor color profile stuck to Dark Monkey

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/sdk#457]
Editor color profile stuck to Dark Monkey. This is a regression. I use mostly Flatlaf Light all around. But try setting it now in current master. After restarting the IDE it is back to Dark Monkey...

![image](https://user-images.githubusercontent.com/8344766/213880707-0cc04700-cba4-4c99-8d13-cfc290fbb099.png)

**Comment by neph1** [comment]
Most likely coming from: https://github.com/jMonkeyEngine/sdk/pull/450 ?

**Comment by tonihele** [comment]
I would imagine so....

**Comment by neph1** [comment]
@peedeeboy will you have time to look at this?

**Comment by peedeeboy** [comment]
Yep - silly bug on my part.  See #458 for explanation and fix - testing always gratefully received :+1:
