### ISSUE TITLE
Update to jme 3.6

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#461]
A list of things to do to upgrade for the new release

* Update gradle.properties to 3.6.0 - I've done this locally, using beta1 for now. If it's of any use, I'll push it.
* Update splash screen. Does anyone have this in an open format? I can open it in gimp, but the layers are rasterized. Font used?
* Update gradle wizard with 3.6?
* ?

**Comment by MeFisto94** [comment]
Two optional things / things to consider:
- create a v3.5 branch that points to current HEAD, that is, if we ever want to release patches to v3.5 while working on 3.6 anyway.
- The netbeans repository currently only has 3.3 and nightly as branches/release channels, but that's also okay I guess.

**Comment by tonihele** [comment]
> * Update splash screen. Does anyone have this in an open format? I can open it in gimp, but the layers are rasterized. Font used?

I tried to do this once. Convert to open format. I could not figure out an automated way. This would be a welcome change. But needs work and probably changes a bit (font maybe need to be changed?). Well, not super difficult. @nickidebruyn has so far always kindly enough updated it.

**Comment by neph1** [comment]
Would be nice if we could update it with a script. Like an empty version box that gets filled. Then we could have "build number", or whatever, too.

**Comment by neph1** [comment]
It should somehow be possible using ffmpeg:

![image](https://user-images.githubusercontent.com/7988802/219852981-3ae29d18-f118-4507-b434-5e2be4a90fe7.png)

Ref:
https://superuser.com/questions/1703971/drawing-text-on-a-gif-while-preserving-transparency-ffmpeg

https://superuser.com/questions/939357/how-to-position-drawtext-text

I'll see if this can be made into an acceptable solution.

**Comment by neph1** [comment]
Ref discussion in Discord. I've replaced the text in the splash, and updated the gif files. I saved the result as xcf. Are the actual psd's used anywhere? They don't look like the gif splash.

**Comment by tonihele** [comment]
I don't think the PSDs are used anywhere.

This was the process last time:
https://github.com/jMonkeyEngine/sdk/commit/c032845cc21806fb969ce24212e995c864ea1bc5

**Comment by tonihele** [comment]
Java 17 is also a big change. LWJGL 2 thing in jME 3.6. Yeah, beta releases or what you are going to call them would be good.

Java 17 alone requires a note in release notes. Gradle templates made with previous versions wont work. They don't support Java 17. User needs to manually install JDK 11 if they want to continue using those as is.

**Comment by neph1** [comment]
I mostly meant for the developers, but maybe this warrants a pre-release (in the chance someone will want to download and test it)
