### ISSUE TITLE
Material editor is completely broken

### ISSUE THREAD

**Issue by Robbi-Blechdose** [jMonkeyEngine/sdk#466]
When starting a new gradle project, then adding a material, there are multiple issues:
- The material can't be opened with a double click, right click -> Open works though
- The material editor tabs "Options" and "Textures & Colors" are empty. "Additional RenderState" has some properties.
- The "Material Definition" Dropdown is empty, even though a new material is based on Lighting.j3md.

**Comment by neph1** [comment]
I think this might be several issues.
The empty "textures & colors" was a bad regression in 3.5.2. It should be fixed in https://github.com/jMonkeyEngine/sdk/releases/tag/v3.5.2-stable-sdk2v3
Empty material definitions is an issue with gradle projects. Should be fixed in the upcoming release.

**Comment by Protoxy22** [comment]
I have a bug too, I'm unable to edit a material and open a scene editor.
On the latest github release

**Comment by neph1** [comment]
Strange. Probably a different issue, but can you make sure that the modules Material Editor and SceneComposer are enabled in Tools/Plugins?
![image](https://user-images.githubusercontent.com/7988802/216901657-998de5a8-5928-4233-a3e0-a611ca01bafc.png)

Did you install it on top of an old version?

**Comment by Protoxy22** [comment]
They are installed an enabled, it's one the first time I use JMonkeyEngine SDK, maybe I mistaken something
On few outdated tutorial videos of the sdk they double click on a material or a scene file and the editor automatically shows up.
Nothing happen on my part

**Comment by tonihele** [comment]
> They are installed an enabled, it's one the first time I use JMonkeyEngine SDK, maybe I mistaken something
> On few outdated tutorial videos of the sdk they double click on a material or a scene file and the editor automatically shows up.
> Nothing happen on my part

Can you take a screenshot for us? To show your project structure and what are you trying to double click. We would need to know is it Ant or Gradle project, what are the file types and that kind of stuff.

**Comment by Protoxy22** [comment]
![image](https://user-images.githubusercontent.com/30320751/217038600-55622c16-97ff-4bbb-a8dc-14b81a220e9e.png)
![image](https://user-images.githubusercontent.com/30320751/217039701-d8e879f2-3486-4c89-a2a1-8c97e7c5c06d.png)

I tested for material and scenes, no editor shows up

**Comment by tonihele** [comment]
> ![image](https://user-images.githubusercontent.com/30320751/217038600-55622c16-97ff-4bbb-a8dc-14b81a220e9e.png) ![image](https://user-images.githubusercontent.com/30320751/217039701-d8e879f2-3486-4c89-a2a1-8c97e7c5c06d.png)
> 
> ![image](https://user-images.githubusercontent.com/30320751/217040110-e69c8bff-ae60-4b9e-a163-82db9e6a27ad.png)
> 
> I tested for material and scenes, no editor shows up

Ok, Gradle project. Your problem has two specific things:

- It needs to be in certain format (you can try the SDK Gradle wizard to create a Gradle project for you). Separate project for assets
- In this version still there was something off with the Gradle projects and material editor and scene editor :( That is already fixed in the master, but should you still encounter a problem with this.. unfortunately you need to wait for the next release (or build SDK from sources)

**Comment by Protoxy22** [comment]
Thank you for the information !
I have no problem with building from the master sources

Have a great evening

**Comment by tonihele** [comment]
> Thank you for the information ! I have no problem with building from the master sources
> 
> Have a great evening

You too and tell us how it went :)

**Comment by neph1** [comment]
>     * The material editor tabs "Options" and "Textures & Colors" are empty. "Additional RenderState" has some properties.
> 
>     * The "Material Definition" Dropdown is empty, even though a new material is based on Lighting.j3md.

This is reproducible in 3.5.2-sdk2 for gradle based projects. Not present in master. So will be fixed in 3.6.

Please reopen if solution is not acceptable, or if it still occurs in 3.6
