### ISSUE TITLE
Font creator multi paging and settings

### ISSUE THREAD

**Issue by neph1** [jMonkeyEngine/sdk#478]
When trying to generate fonts, I can't get the plugin to generate more than one page (if choosing very large size).
Neither does it seem to read the settings regarding char range. It always generates all characters.

**Comment by tonihele** [comment]
Issue as old as time itself: https://github.com/jMonkeyEngine/sdk/issues/6 :D

**Comment by neph1** [comment]
D:

**Comment by tonihele** [comment]
But also an easy fix, so we should just roll our sleeves. Nothing complicated with the Font Creator. I can try to take a look at some point. Not very soon though...
