### ISSUE TITLE
Upgrading bundled Nifty

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#48]
See jMonkeyEngine/jmonkeyengine#330, since the core is basically decoupled from Nifty it's our responsibility to use the more recent version and also upgrade the templates or whatever is needed.

**Comment by shadowislord** [comment]
Not exactly sure how you can upgrade nifty for the SDK without updating it for the engine.
In any case, we should not use snapshot versions of nifty gui. Perhaps it is better to wait for 1.4.2 to be released.

**Comment by MeFisto94** [comment]
Well I was thinking that Nifty is treated as an external library (since it's maven repo is in the build.gradle), so my guess was it's jar is simply packaged and used.

On the other hand I guess nifty has some jme-specific code which seems to reside in the engine.
Anyway if you look into the issue on nifty-gui/nifty-gui#364 void256 says that he see's no problem with using SNAPSHOT in JME (but of course it's up to you to decide)

**Comment by void256** [comment]
... yes, as outlined in this comment: https://github.com/nifty-gui/nifty-gui/issues/364#issuecomment-204750530 and under certain restrictions explained in that comment ONLY. And not in general! Of course it's always best to use a released version!

We've been here before and we don't want to delay any JME-release waiting for a Nifty release since chances are that both usually don't align.

**Comment by grizeldi** [comment]
1.4.2 is out for about a year and a half now. Where will we update it? In the sdk or in the engine? Or we just continue using current version since not a lot of people use nifty anyway?

**Comment by MeFisto94** [comment]
The engine would have to update it's dependencies. I'm guessing here but I guess the Nifty dependency the SDK has is only the Nifty Visual Editor and `jme3-nifty-gui` will pull in the appropriate nifty version itself.

**Comment by MeFisto94** [comment]
`corelibs dep("org.jmonkeyengine:jme3-niftygui:$jmeEngineVersion", true, true)` -> we depend on Nifty via the engine, nothing more, so this issue is solved.
Plus: The Engine already uses 1.4.2, so jMonkeyEngine/jMonkeyEngine#330 is also solved.
