### ISSUE TITLE
 3.1-alpha4-SNAPSHOT unable to deploy on android device (Troubleshooting)

### ISSUE THREAD

**Issue by doitwrong** [jMonkeyEngine/sdk#51]
I have created plain new jmonkey project from the wizard, enable android android deployment, installed Android SDK Manager set configuration on Android Device and yet the default emulator is executed. ( I m pretty sure that I set my device because on jmonkey 3.0 I`ve managed to deploy it on device)

**Comment by doitwrong** [comment]
disable "Compile on Save" option, fixed the strange behavior. It`s not bug i guess.

**Comment by MeFisto94** [comment]
Actually we didn't change a thing from 3.0 to 3.1 but it's strange.
Compile on Save is sometimes error inducing, yes, but usually a Clean & Build should fix that.

It should affect .class files though and not some config file which defines whether the Emulator is executed or not.

**Comment by normen** [comment]
For android this has to be disabled so all changes actually go to the jar files which are moved to the android project.
