### ISSUE TITLE
ViewPort is not recreated/reset by opening another j3o file

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#525]
If I change the background color of the `ViewPort `via an `AbstractControl`, the color is permanent even if I open another j3o file. 
Any added SceneProcessors are also permanent. Something in memory that is not reset?

First I create a scene and add my custom AbstractControl to the rootNode.
![img1](https://github.com/jMonkeyEngine/sdk/assets/32201701/66d0b329-7aea-47e9-94a6-d76fe91141b0)

I close the scene without saving, and then open another j3o file.
![img2](https://github.com/jMonkeyEngine/sdk/assets/32201701/0861446d-32e2-4fed-acfe-4e1285235cf6)

```java
public class ViewPortControl extends AbstractControl {

    private ViewPort viewPort;
    private boolean initialized = false;
    // Set the viewport's background color to light blue.
    private ColorRGBA skyColor = new ColorRGBA(0.1f, 0.2f, 0.4f, 1f);

    @Override
    protected void controlUpdate(float tpf) {
        if (!initialized && viewPort != null) {
            initialized = true;
            setupShadowRenderer();
            setSkyColor(skyColor);
        }
    }

    private void setupShadowRenderer() {
        AssetManager assetManager = new DesktopAssetManager(true);

        DirectionalLight light = new DirectionalLight();
        light.setDirection(new Vector3f(-1f, -1f, -1f).normalize());
        ((Node) spatial).addLight(light);

        DirectionalLightShadowRenderer dlsr = new DirectionalLightShadowRenderer(assetManager, 1024, 3);
        dlsr.setLight(light);
        dlsr.setLambda(0.55f);
        dlsr.setShadowIntensity(0.8f);
        dlsr.setEdgeFilteringMode(EdgeFilteringMode.Bilinear);
        viewPort.addProcessor(dlsr);
    }

    @Override
    protected void controlRender(RenderManager rm, ViewPort vp) {
        if (viewPort == null) {
            viewPort = vp;
        }
    }

    public ColorRGBA getSkyColor() {
        return skyColor;
    }

    public void setSkyColor(ColorRGBA skyColor) {
        this.skyColor.set(skyColor);
        viewPort.setBackgroundColor(skyColor);
    }

}
```

**Comment by capdevon** [comment]
Is there any update on this bug?

**Comment by neph1** [comment]
I'm afraid I haven't looked into it. I assume it would be simple to fix, though; setting the background color to 'default' on scene open. Most likely the context is kept, ie app not restarted when loading a new scene, so things like that are not reset.

**Comment by capdevon** [comment]
_"The app and context are not restarted when a new scene is loaded"_ 

This is very strange, I don't understand why. If you're not going to restart the app (I'd prefer the SDK to do this), I'd suggest restoring the initial settings each time a new scene is opened (i.e. resetting the viewport **background color** and resetting the associated **processors**). If you read the sample code above, I added a `DirectionalLightShadowRenderer `to the viewport processors. The **processors** should be reset as well. Another important thing: **appStates** should also be detached and reset. This is not happening.
