### ISSUE TITLE
Cannot access MotionState

### ISSUE THREAD

**Issue by ZakharD** [jMonkeyEngine/sdk#53]
Class : src\jme3test\bullet\PhysicsHoverControl.java:175
error: cannot access MotionState
  getMotionState().applyTransform(spatial);
  class file for com.bulletphysics.linearmath.MotionState not found

**Comment by normen** [comment]
You're somehow mixing jbullet and native bullet.

**Comment by ZakharD** [comment]
I do not mix. I just downloaded the SDK alpha 3 from GitHub. The missing link libraries jbullet.jar

**Comment by MeFisto94** [comment]
We actually have this issue for a few parts of the SDK, I just didn't have the time to look into it :(

**Comment by ZakharD** [comment]
It is treated by adding jbullet.jar. Good engine, like stability

**Comment by ZakharD** [comment]
When will the transition to lwjgl 3?

**Comment by MeFisto94** [comment]
See the Forums for that, I guess it's already possible, you just need to change some variables and build the engine yourself
