### ISSUE TITLE
JME v3.6.1-stable-sdk3_assetbrowser_alpha

### ISSUE THREAD

**Issue by dronicfore** [jMonkeyEngine/sdk#540]
I downloaded the JME [v3.6.1-stable-sdk3_assetbrowser_alpha](https://github.com/jMonkeyEngine/sdk/releases/tag/v3.6.1-stable-sdk3_assetbrowser_alpha) and realized 2 major problems.

1. It does not has the iOS deployment plugin by default under Project Properties. Although, i know this is a plugin that can be activated or downloaded according to this [official documentation](https://wiki.jmonkeyengine.org/docs/3.4/sdk/ios.html) but at least this plugin should always be there to create awareness for unexperienced users (newbies) that JME has the power to deploy our games/apps into the Apple iOS mobile platform.
2. This version throws **IllegalMonitorStateException** whenever i try to run the **JMETest** or **BasicGame** package.
![IMG_20231001_002001-picsay](https://github.com/jMonkeyEngine/sdk/assets/39514547/12bdd27e-2276-4e1f-94c3-83e4a4ad1449)

My laptop has Windows 8.1 with Intel HD Graphics Card and Open GL 2.1.

**Comment by neph1** [comment]
I think it's a Mac specific problem with LWJGL. Do you know how to run the app with VM options? Try adding:
`-XstartOnFirstThread` as in `DEFAULT_JVM_OPTS="-XstartOnFirstThread"`
I don't have a clean example of how it's used in gradle.

If you're running with Ant, you can add it if you right click the project and select Properties.
Scroll down to "Run" and add it in VM Options.

Some reference:
https://github.com/LWJGL/lwjgl3/issues/311

**Comment by tonihele** [comment]
With Gradle, using the application plug-in, it is just:
```
application {
    applicationName = 'MyApp'
    mainClass = 'myapp.Main'
    applicationDefaultJvmArgs = ["-Dvisualvm.display.name=MyApp -XstartOnFirstThread"]
}
```

**Comment by tonihele** [comment]
If you want to do iOS development, I think you need to go as far back as SDK 3.3. iOS is not an easy platform to support. You can track its status from here: https://github.com/jMonkeyEngine/jmonkeyengine/issues/1611

**Comment by tonihele** [comment]
> new asset viewer & which is still buggy

Please report bugs on their own issues if you found some.

Thank you for this bug report. There seems to be some confusion since this has 2 totally different issues. One which has nothing to do with the SDK or MacOS (we were thrown of by iOS and thread problem I suppose..) and one which deserves its own ticket.

Therefore I'm closing this issue. The following issue was created to jME: https://github.com/jMonkeyEngine/jmonkeyengine/issues/2077
