### ISSUE TITLE
Error while deleting an AnimClip

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#577]
If you `delete` an animation that is currently playing, the character continues to move with the deleted animation and the animation tree breaks oddly showing empty icons at the removed animation.

Perhaps the correct order of operations should be:
```java
                if (animComposer.getCurrentAction() == animComposer.getAction(clipName)) {
                    animComposer.reset();
                }
                AnimClip clip = animComposer.getAnimClip(clipName);
                animComposer.removeAction(clipName);
                animComposer.removeAnimClip(clip);
                refreshAnimTree();
```

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/228ee374-8bdb-4db1-b06e-c42c81c72a0b)

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/0704e534-530c-4c0c-90cf-4b0d840b46ac)

**Comment by neph1** [comment]
Which class is that?

**Comment by capdevon** [comment]
I don't know, the code snippet is just a guess I made.
