### ISSUE TITLE
Primitives menu: add WireBox, WireSphere and Torus

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#582]
Hi guys,
Could the following Meshes be added to the Primitives menu? `WireBox`, `WireSphere` and `Torus`.

Here is an example image from my editor.

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/b9fbe3d6-daeb-4ee3-9be4-d3fb66db9cf2)

Thanks

**Comment by neph1** [comment]
:hot_face:
