### ISSUE TITLE
NPE when adding CharacterControl to the Spatial

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#587]
Hi guys,
After adding the CharacterControl to the Spatial, the SDK raises an Exception and you can no longer open other models and have to restart the editor.

![NPE add CharacterControl](https://github.com/jMonkeyEngine/sdk/assets/32201701/7b5e2edd-3d72-4a12-a2db-9033c64881fe)

![NPE add CharacterControl SDK crash](https://github.com/jMonkeyEngine/sdk/assets/32201701/a8584fc7-80fd-4d70-8829-f66c0a0d3cc3)

**Comment by tonihele** [comment]
`java.lang.NoSuchMethodException: com.jme3.bullet.control.CharacterControl.getCollisionShape()`

Yeah, it can't find this `com.jme3.bullet.collision.PhysicsCollisionObject#getCollisionShape` method. Is it because `PhysicsCollisionObject` is abstract? It is using `getClass().getMethod(getter)`

**Comment by tonihele** [comment]
Oh yes, because we are using Minie. Not jME's bullet. Confusing when the packages are the same and all that...
