### ISSUE TITLE
Filters Don't Display in SDK FilterExplorer

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/sdk#59]
Filters added to a .j3f file don't show up in the FilterExplorer. When I load the filters in the game, however, they appear present. This happens in multiple L&Fs. It is still possible, however, to add filters by the usual method of right-clicking on the "filter" node and selecting the filter's name.

![screenshot from 2016-04-23 09-54-48](https://cloud.githubusercontent.com/assets/3982497/14762170/9e2c20f4-0939-11e6-976a-36e8ff407c03.png)

**Comment by normen** [comment]
How else do you add filters? oO

**Comment by john01dav** [comment]
@Normen The filters can be added normally (right-click on filters then click on the filter name), but they don't display. I'll try to make a video to show it.

**Comment by john01dav** [comment]
@normen 
Here's a video:
https://www.youtube.com/watch?v=UbKf9lvUlfY

Notice how I add a filter to the effects.j3f file, and it doesn't show. But, when I attempt to show it in the scene composer, it does.

**Comment by Dokthar** [comment]
the problem is resolved, it will be available soon in the next snapshot.
Thanks again for reporting issues.
