### ISSUE TITLE
MaterialEditor: MorphWeights - wrong parameter type.

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#594]
Hi guys,
the `MorphWeights` parameter is a `FloatArray` not a `Float`. 

See [PBRLighting.j3md](
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md#L124)
```java
        // For Morph animation
        FloatArray MorphWeights
        Int NumberOfMorphTargets
        Int NumberOfTargetsBuffers
```
Its representation in the Options tab of the Material Editor is wrong. 
![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/137fb4b2-972b-44e8-813d-59febba3c7fe)

The problem should be caused by the incorrect `defLine.startsWith(string)` and `defLine.replaceFirst()` algorithm when `string = "Float"` and defLine starts  with `FloatArray`:

https://github.com/jMonkeyEngine/sdk/blob/master/jme3-materialeditor/src/com/jme3/gde/materials/EditableMaterialFile.java#L243
```java
    private static final String[] variableTypes = new String[]{
            "Int", 
            "Boolean", 
            "Float", 
            "Vector2", 
            "Vector3", 
            "Vector4", 
            "Color", 
            "Texture2D", 
            "Texture3D", 
            "TextureArray", 
            "TextureBuffer", 
            "TextureCubeMap" };
```

```java
        for (String string : variableTypes) {
            if (defLine.startsWith(string)) {
                final String propName = MaterialUtils.trimName(defLine.replaceFirst(string, ""));
                matDefEntries.add(propName);
                ...
            }
        }
```

Output:
MaterialProperty [type=Float, name=Array ShadowMapSize, value=]

**Comment by tonihele** [comment]
I don't know would be easier to parse the file with StringTokenizer or something. But I think the easiest fix is to set FloatArray as one of the types. It just needs to be before Float (startsWith...), need to comment this in code. Do we have editor type for float array...
