### ISSUE TITLE
MaterialEditor: Duplicate Items in the MatDefs Selection Dropdown Menu.

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#597]
![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/c9dea8b6-8b88-4e68-9d60-034f26213d76)

**Comment by tonihele** [comment]
Hmm yeah, I have no idea how this situation has occurred. It would be easy to just implement a naive fix to remove the duplicate entries. However, I don't think that is a proper solution.

Could you @capdevon debug this? Is this repeatable occurrence?

**Comment by neph1** [comment]
Iirc it's been like that for a long time. I'll take a look at it

**Comment by capdevon** [comment]
thank you guys for the support
