### ISSUE TITLE
MaterialEditor: unable to edit the name of the Material

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#598]
If I change the name of the material in the text input component, the `Source Tab` is not updated with the new name and saving the file, the change is not permanent and always reports `My Material`

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/f29708b0-8f5f-4f5b-9905-96be67f3e30d)

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/2fb5d2e3-e682-460b-9fac-97a9a5ece8c7)

**Comment by tonihele** [comment]
Probably https://github.com/jMonkeyEngine/sdk/blob/master/jme3-materialeditor/src/com/jme3/gde/materials/EditableMaterialFile.java#L466, instead of constant it should just use the `name` variable.

**Comment by capdevon** [comment]
thank you guys for the support
