### ISSUE TITLE
CTRL+S in SceneComposer activates scaling of selected object

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/sdk#60]
As the title says, using the CTRL+S key combination to save the current scene triggers the scaling operation on the selected spatial as well as [appearing to](https://hub.jmonkeyengine.org/t/stability-issues-with-sdk-saving/35724) save.

**Comment by Dokthar** [comment]
resolved in dfca62fc45462a57b95b3e0eca42ceaec11e01df , it will be available in the next snapshot
