### ISSUE TITLE
Duplicate Common Materials file in scene dropdown menu

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#606]
Hi guys, can you please verify this issue? 
The personal files don't seem to be duplicated. Just the common ones.

Thanks

![image](https://github.com/jMonkeyEngine/sdk/assets/32201701/da1162fa-f744-42e4-8d85-e8e994188a1f)

**Comment by capdevon** [comment]
Ok, let me know if I can close this report or if you want to investigate further.

**Comment by neph1** [comment]
No, I can reproduce it
