### ISSUE TITLE
Opening this scene freezes the SDK

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/sdk#63]
When I open this scene, the SDK freezes for several seconds. The OpenGL scene composer is sometimes made visible before the freeze happens, in which case the water in the scene keeps on moving but I can't interact with either it or the rest of the SDK.

[scene.zip](https://github.com/jMonkeyEngine/sdk/files/257127/scene.zip)

**Comment by john01dav** [comment]
![screenshot_20160510_074528](https://cloud.githubusercontent.com/assets/3982497/15146886/430e41f0-1683-11e6-96c1-3a9bf5f09ba4.png)
This error occurs when opening it in the terrain editor. There doesn't seem to be any way to copy/paste the text out of the dialog.

**Comment by normen** [comment]
You're simply running out of direct memory, you can increase that in the jmonkeyplatform.conf file.

**Comment by MeFisto94** [comment]
Also see here:
https://wiki.jmonkeyengine.org/doku.php/sdk:increasing_heap_memory

Without having viewed the file: Your Scene might be huge and you might consider splitting it in parts where possible and only merge it in the game itself (and maybe not even there, only load parts of it)
