### ISSUE TITLE
Issue with Custom Controls and AppStates in Jme Gradle Projects and SceneEditor

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/sdk#640]
Hi guys, I am converting some pipelines from Ant projects to Gradle projects. Unfortunately, in Jme Gradle projects it is not possible to add Custom Controls or Custom AppStates in the SceneEditor when viewing 3D models. These two features would be really useful. Could you kindly take a look at the problem?

https://hub.jmonkeyengine.org/t/help-needed-with-j3o-sdk-functions/48036/9

**Comment by tonihele** [comment]
Looks like jme3-core\src\com\jme3\gde\core\appstates\NewAppStateVisualPanel1.java#getSources is a bit more complicated with Gradle projects. With the SDKs default Gradle project structure as well the models are in a different module than the actual source files it is trying to find. We need to actually traverse the modules...

**Comment by tonihele** [comment]
Phew, never used or saw these features before. You should be SDK developer instead. I think I got it, but could you verify? By checking out https://github.com/tonihele/sdk/tree/bugfix/issue-640. Running instructions: https://github.com/jMonkeyEngine/sdk?tab=readme-ov-file#building-the-sdk. But essentially as you would do for any Gradle app.

**Comment by capdevon** [comment]
Hi Toni, you're very close to the solution! With your recent changes, both BaseAppState and AbstractControl are now visible in the selection windows. However, when clicking the 'Finish' button to add them to the scene, the operation fails due to the class not being found. Please see the attached screenshots for the error messages.

### Test AbstractControl:
![image](https://github.com/user-attachments/assets/b3708826-4264-4179-b007-732fc890d786)

![image](https://github.com/user-attachments/assets/1eab859a-6f09-4402-9b36-776e66ba78f6)

### Test BaseAppState:
![image](https://github.com/user-attachments/assets/b8e07325-28c4-4250-858d-b1abcd54ce5f)

![image](https://github.com/user-attachments/assets/a24ddac1-0e9d-45f9-946f-0a2a7bde35ef)

**Comment by tonihele** [comment]
Did you build the project before? That was at least a requirement for me. Ant projects build themselves all the time thus the compiled class is found. Not so much the Gradle ones...

**Comment by capdevon** [comment]
Okay, that was it, I ran the project build with Gradle and it works

**Comment by tonihele** [comment]
Great, thanks! I'll create a PR.
