### ISSUE TITLE
Node doesn't update in editor when model is added.

### ISSUE THREAD

**Issue by jojoofu** [jMonkeyEngine/sdk#66]
When you create an empty node in the scene editor then add a model to it via right click add to scene the node doesn't update immediately. The model is added but will not be shown until you update the node again by adding a control or something else to it.

**Comment by MeFisto94** [comment]
Does it work when clicking on the "update" button in the upper left?

**Comment by jojoofu** [comment]
Yes , I never noticed that until now. It still seems like it should update automatically though.

**Comment by Dokthar** [comment]
i'll take a look at this.

**Comment by Ali-RS** [comment]
I also had not noticed that "update" button. :smile: 
Thanks .
