### ISSUE TITLE
Add maven import option to ANT projects

### ISSUE THREAD

**Issue by normen** [jMonkeyEngine/sdk#70]
As some external libraries for the engine probably won't be wrapped as SDK plugins it would make sense to add an option to include maven artifacts into SDK projects. Theres ANT tasks for this purpose, see http://wiki.netbeans.org/FaqMavenAntTasks

In addition to adding the ANT libraries and tasks there should be a project configuration panel to easily add new maven artifacts. Furthermore it should be made sure that the libraries integrate properly into the rest of the build process (manifest generation, library copying etc.)

**Comment by MeFisto94** [comment]
Since we plan to migrate to gradle, this comes in "for free", for gradle projects at least.
