### ISSUE TITLE
SDK updater can't connect

### ISSUE THREAD

**Issue by Robbi-Blechdose** [jMonkeyEngine/sdk#72]
I downloaded and installed the latest release, and saw that the SDK could not update internally. When I went to "Plugins->Check for Updates" though, it gave me this: "Unable to connect to the jMonkeyEngine SDK Stable because of http://updates.jmonkeyengine.org/stable/3.1/plugins/updates.xml".
I also tried opening this in my browser, and there's a github page saying that page doesn't exist.

**Comment by grizeldi** [comment]
That's because original site is down I think.

**Comment by MeFisto94** [comment]
That's exactly the case. Unfortunately our infrastructure is currently down so the updates don't work.
Note: Actually only the nightly updates worked anyway (for some reason the sdk didn't consider our updates newer than the local version), so we'd need to work on that a bit longer. 

But: we can't test it currently for obvious reasons
