### ISSUE TITLE
Exception: Direct Buffer Memory

### ISSUE THREAD

**Issue by Robbi-Blechdose** [jMonkeyEngine/sdk#85]
I'm using SDK 3.1-beta1, and sometimes when I try to open a scene in the scenecomposer, it just show me "Exception: Direct Buffer Memory" and doesn't open the scene. This only occurs after previously having opened a scene. It is fixed by a restart of the SDK, but really unnerving.

**Comment by MeFisto94** [comment]
@Nehon @shadowislord @pspeed42 
This sounds somewhat like a problem with Engine Interna. Do you guys have a clue?

Can you maybe proide a model or does it happen with all models?

**Comment by pspeed42** [comment]
Probably it was an OutOfMemory error based on the message.  The error
dialog unhelpfully doesn't show anything but the message but that's my
guess.  Meaning previous models weren't GC'ed before trying to load the new
one.

**Comment by MeFisto94** [comment]
AHH true! This could simply be an OutOfMemoryException instead of some Issue related to our DirectMemoryBuffer System and such. 

See [this](https://github.com/jMonkeyEngine/sdk/issues/63#issuecomment-218388198) then.
The Problem is the wiki link is broken :(

**Comment by MeFisto94** [comment]
Hey, @Robbi-Blechdose could you fix it by increasing heap memory?

**Comment by Robbi-Blechdose** [comment]
@MeFisto94 Yes, that fixed it.
