### ISSUE TITLE
Updgarde Proguard from 4.7 to 5+ to support Java 1.8

### ISSUE THREAD

**Issue by abcde13** [jMonkeyEngine/sdk#87]
Currently the SDK comes bundled with Proguard 4.7, which doesn't support Java 1.8. If I use Java 1.8 for my projects, I get: 

`/nbproject/obfuscate-impl.xml:7: Can't read [~/jmonkeyplatform/jdk/jre/lib/rt.jar] (Can't process class [com/oracle/net/Sdp$1.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))`

However, Proguard versions above 5.0 now support Java 1.8. It would be nice to upgrade the SDK plugin to a version above 5.

@normen suggested I make an issue for this.

**Comment by Ali-RS** [comment]
Thanks
