### ISSUE TITLE
Include Avian into the SDK Release

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/sdk#91]
Hey Guys,
I have this on my list and I'm simply keeping this issue as documentation for coming generations of monkeys ;) 

So in short: Avian is our JRE for iOS and it has to be built on a Mac-Computer. As such we can't build it with travis (since it's also a bit troublesome. See `build_avian.sh` inside of the jme3-ios folder). 
It used to be a plugin and from todays point of view I should've kept it like that.

The reason is that avian is now over 100MiB huge however completely useless for people not wanting iOS.
I might remove it again, when our Plugin Structure is up and working again, we'll see. For now it is an additional overhead for everyone.

Since that file is to big to be used in our git (And this is good, because else every checkout would take ages), I've opened some bintray repo/storage/whatever under my name (Which will be moved to our official bintray some day)

I'll include it to be downloaded by travis, for this I'll include some mechanism to check the version, so you can update travis by simply changing a variable to "1.3" and then it deletes the 1.2 avian from the travis cache and redownloads the avian 1.3 version. See here https://bintray.com/mefisto94/jme-sdk-storage/avian-openjdk-mac

**Comment by grizeldi** [comment]
And when is plugin structure supposed to be up and running again?

**Comment by MeFisto94** [comment]
To quote normen/nehon:
https://www.youtube.com/watch?v=bgujPDBmAY0

The Problem is we need to overthink stuff. I'd love to have our dedicated server up and running again but since our team is changing we don't want the same thing to happen again. My Idea was to "abuse" bintray for that but we have to check the ToS and everything and I'm still to busy.

See this issue?
It's a matter of "if !file exists then download end; delete other versions; copy version to name-without-version.zip" but a) nobody is really working on the SDK currently and b) I had to take a break from gradle buildscripts. It's not my favourite job.
