### ISSUE TITLE
Scenecomposer's FilterExplorer is broken

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/sdk#92]
So I wanted to add a water filter to my scene just to see how it would look.
Checked out this [youtube video](https://www.youtube.com/watch?v=lTTX1gopuIE) and he used the FilterExplorer tab next to the SceneExplorer. However in current version of sdk opening the FilterExplorer tab only displays an nameless tree node with a blank piece of paper icon and right clicking on it does nothing.

Having that back would be great, since it allows quick preview how the scene would look with a filter.

**Comment by normen** [comment]
First off, this is an issue tracker, not a troubleshooting section, thats what the forum at hub.jmonkeyengine.org is for.

As for your problem, create a new filter file (j3f) in your assets via the new File menu and open it, thats when you can add new filters to it in the FilterExplorer.

**Comment by grizeldi** [comment]
Okay, sorry. I thought this was a bug.
