### ISSUE TITLE
error: diamond operator is not supported in -source 1.6

### ISSUE THREAD

**Issue by nordfalk** [jMonkeyEngine/sdk#94]
When creating a new JME project (or JmeTests) I can see that nbproject/project.properties contains:
javac.source=1.6
javac.target=1.6

![image](https://cloud.githubusercontent.com/assets/1143272/18685549/d91f7ba6-7f78-11e6-90bd-2c473d71b223.png)

This default setting gives errors like:

warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/j/3D-briller/jme_proj_3.1-beta1-b002-

SNAPSHOT/JmeTests/src/jme3test/app/TestCloneSpatial.java:176: error: diamond operator is not supported in -source 1.6

So, please change all the new project templates's values to
javac.source=1.8
javac.target=1.8

**Comment by nordfalk** [comment]
This is with 3.1-beta1-b002-SNAPSHOT as well as the previous 3.1 beta version

**Comment by grizeldi** [comment]
Yeah this bugs me too. Could we set it to at least java 7, since java 6 is obosletely obsolete already?

**Comment by pspeed42** [comment]
We wait your patches.

**Comment by grizeldi** [comment]
There, PR made.
