### ISSUE TITLE
JM3 Tests project won't compile (3.1-beta1-b002-SNAPSHOT)

### ISSUE THREAD

**Issue by nordfalk** [jMonkeyEngine/sdk#95]
Create a new JM3 Tests project

![image](https://cloud.githubusercontent.com/assets/1143272/18685828/fa7d6fe6-7f79-11e6-8919-9fb1d95bf282.png)

I get (with 3.1-beta1-b002-SNAPSHOT and 3.1-beta1)

```
ant -f /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests -Dnb.internal.action.name=rebuild clean jar
init:
deps-clean:
Updating property file: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/built-clean.properties
Deleting directory /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build
clean:
init:
deps-jar:
Created dir: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build
Updating property file: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/built-jar.properties
Created dir: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/classes
Created dir: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/empty
Created dir: /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/generated-sources/ap-source-output
Compiling 258 source files to /home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/build/classes
/home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/src/jme3test/bullet/PhysicsHoverControl.java:187: error: cannot access MotionState
            getMotionState().applyTransform(spatial);
  class file for com.bulletphysics.linearmath.MotionState not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
/home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/nbproject/build-impl.xml:521: The following error occurred while executing this line:
/home/j/3D-briller/jme_proj_3.1-beta1-b002-SNAPSHOT/JmeTests/nbproject/build-impl.xml:219: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)

```

Possible fix: Comment out the offending line ;-)

```
   public void update(float tpf) {
        if (enabled && spatial != null) {
//            getMotionState().applyTransform(spatial);
        }
    }

```

**Comment by MeFisto94** [comment]
So I've investigated that a bit: When you remove `jme3-jbullet` and add `jme3-bullet` and `jme3-bullet-native` OR when you add `jbullet.jar` to `jme3-jbullet` this works.

This means:
a) We could hack a bit in the gradle file so that it adds jbullet.jar to jme3-jbullet so that it contains the jbullet.jar file. This would be the proper way
b) Since we want to deprecate jBullet, just change the Test Templates to use Bullet Native.

I think we should go for b).
If someone wants, he can nevertheless submit a Pull Request for the correct jme3-jbullet.
The Gradle File contains a part where all dependencies are taken and somehow added into the netbeans xml/properties scheme. One needs to find out where and then add the jbullet.jar there.

Note though, that this isn't necessary since in the near future that dependency might completely drop.

**Comment by pspeed42** [comment]
Not sure what you mean by this:
"a) We could hack a bit in the gradle file so that it adds jbullet.jar to jme3-jbullet so that it contains the jbullet.jar file. This would be the proper way"
...both of my interpretations seem bad.

**Comment by MeFisto94** [comment]
Well, I think the gradle file does this:
You define the dependencies which are then downloaded. Then it grabs these dependencies and per dependency it creates a netbeans lib and references the downloaded jar files.

jbullet.jar is not part of jme3-jbullet, though, so it is missed out, even though it is present. It is even shipped with the SDK but not packed into that netbeans library.

So we need something like `if dependency.equals("jme3-jbullet") { list.add("jbullet.jar"); }` as a proper fix.

**Comment by pspeed42** [comment]
Well, if this is in SDK-specific stuff then I guess it's ok.  The reason jme3-jbullet doesn't have a direct dependency on jbullet is because jbullet is not in a public repo... so we'd have to also leave jme3-jbullet out of a public repo.  Unless we wanted to be assholes.

**Comment by MeFisto94** [comment]
Yeah the SDK supplies the jBullet.jar but doesn't "merge" it with jme3-jbullet, so when you add jme3-jbullet you get unsatisfied links due to the missing jbullet.jar

**Comment by TheAwesomeGem** [comment]
There are a lot of issues with JM3 Tests.

**Comment by tonihele** [comment]
Unless @TheAwesomeGem cares to ellaborate, it looks to me that stuff is working, Closing.
